/*
 * Copyright (c) 2015, iLearnRW. Licensed under Modified BSD Licence. See licence.txt for details.
 */public enum Tag{
	
	LOGIN,
	LOGOUT,
	LEARN_SESSION_START,
	LEARN_SESSION_END,
	APP_SESSION_START,
	APP_SESSION_END,
	APP_ROUND_SESSION_START,
	APP_ROUND_SESSION_END,
	WORD_SELECTED,
	
	WORD_DISPLAYED,
	WORD_SUCCESS,
	WORD_FAILED,
	
	PROFILE_UPDATE,
	
	GAME_EVENT,
	INTERFACE_INTERACTION,
	ACTIVITY_PROPOSED,
	SAVEFILE
}